name:                gpx-conduit
version:             0.2.1
github:              "githubuser/gpx-conduit"
license:             BSD-3
author:              "Thomas M. DuBuisson"
maintainer:          "Thomas.DuBuisson@gmail.com"
copyright:           "Thomas M. DuBuisson (2012)"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Read GPX files using conduits
category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at https://github.com/TomMD/gpx-conduit#readme

dependencies:
- base >= 4.7 && < 5
- xml-conduit >= 1.10.1.0 && < 2.0.0
- conduit  >= 1.3.6 && < 1.4.0
- conduit-extra >= 1.3.8 && < 1.4.0
- resourcet >= 1.3.0 && < 1.4.0
- attoparsec >= 0.14.4 && < 0.15.0
- time >= 1.12.2 && < 1.13.0
- text >= 2.1.3 && < 2.2.0
- xml-types == 0.3.*
- old-locale == 1.0.*
- filepath >= 1.5.4 && < 1.6.0
- monad-control >= 1.0.0 && < 1.1.0
- void >= 0.7.0 && < 0.8.0
- directory >= 1.3.8 && < 1.4.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  gpx-conduit-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gpx-conduit

tests:
  gpx-conduit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gpx-conduit
